### ISSUE TITLE
doesnt do anything :(

### ISSUE THREAD

**Issue by kkellogg378** [thatDudo/Murder-Mystery-Helper#1]
title says all

**Comment by thatDudo** [comment]
Well at least it doesnt crash or anything.
Im going to look into it later.

**Comment by thatDudo** [comment]
Tested it, it should still work.
If you don't how it functions: Whenever a player grabs his murder weapon he will get a red outline.

If you want more functionality, set a key shortcut for the settings and choose. I did it that way because some might find it annoying if there's to much highlighted. But you can indeed highlight the detectives in blue, all other players in white and the bow in green.

**Comment by thatDudo** [comment]
Just figured out that the glow effect doesn't work with fast render and shaders turned on: https://github.com/sp614x/optifine/issues/3662 .

**Comment by zribe** [comment]
hey, same issue here, i am using IRIS
