### ISSUE TITLE
Mod Usage

### ISSUE THREAD

**Issue by winturs** [thatDudo/Murder-Mystery-Helper#2]
The mod doesn't seem to be working and I can't seem to find any way to open the menu. I'm not sure if there is a shortcut to open it or somewhere where I can create one. Thanks.

**Comment by winturs** [comment]
Partially resolved, I found the settings menu but the glow doesn't seem to be working. Perhaps one of my mods is preventing it from working?

**Comment by winturs** [comment]
I enabled everything but nothing is being highlighted including the gold.

**Comment by winturs** [comment]
Hello? Do you still look at this mod?

**Comment by thatDudo** [comment]
Are you using minecraft version 1.18.2? I havent ported it to newer minecraft versions.

**Comment by winturs** [comment]
Yes I am using 1.18.2, the mod menu shows up and everything is enabled

**Comment by winturs** [comment]
I only have the Fabric API mod and the murder mystery mod for reference.

**Comment by thatDudo** [comment]
I think optifine and potentially some shaders are blocking the native minecraft glowing effect. If you are using those you
should switch to iris/sodium/lithium/phosphor (which are a little better anyways as far as i know).

Ah if you dont have those in im not quite sure what might be the problem...
Maybe you havent used `mc.hypixel.net` as your server address because thats what being used to identify the server.

**Comment by winturs** [comment]
Oh! I'm using a mod for queue stats and such... I think that is the problem. Thank you

**Comment by winturs** [comment]
Did not resolve issue

**Comment by winturs** [comment]
Forgot the mc before the hypixel.net now it is actually resolved
Ty
